# Site settings
title: "Giovanna Severo"
email: giovanna.severo96@gmail.com
description: "."
baseurl: ""
url: "http://giovanna96.github.io"
title_description: "Hi, I am Giovanna, I have a degree in Science and Technology and now I'm a Computer Engineering student at Universidade Federal do Rio Grande do Norte. This is my personal blog where I'll post my projects."
title_image: "https://scontent.fnat1-1.fna.fbcdn.net/v/t1.0-9/21463048_1421336871318440_2094234529809251487_n.jpg?_nc_cat=107&_nc_ht=scontent.fnat1-1.fna&oh=6a299415d2defba4a62df6674a702373&oe=5D1BCB88"
google_analytics: ""
disqus_account: 
github_repository: 
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  giovanna96
instagram_username: giovannasevero
reddit_username: 
linkedin_link: https://www.linkedin.com/in/giovanna-severo-a68191150/
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link: https://www.facebook.com/giovanna.severo.33?ref=bookmarks

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
